--------------------------------------------------------------------------------
-- Generates the self-test's manifest of what this version of the addon has.
--
-- The self-test used to check a list of accessors written by hand, which is a
-- list that rots: add a panel, forget the line, and the check for it silently
-- stops running. This reads the source instead, so the manifest is whatever the
-- addon actually contains at the moment it is built.
--
-- Run it whenever the addon changes:
--
--   lua5.1 tools/manifest.lua
--
-- It writes InomrahsMISelfTest/Manifest.lua, which is data and nothing else.
--------------------------------------------------------------------------------

local SOURCE = "InomrahsMythicInstructions"
local OUTPUT = "InomrahsMISelfTest/Manifest.lua"

-- "--check" compares instead of writing, so the offline suite can fail when the
-- manifest no longer describes the addon. Comparing the text directly rather
-- than asking git, because git says nothing about a file it is not yet
-- tracking — which is how the first version of this check passed while the
-- manifest was a version out of date.
local CHECK_ONLY = (arg and arg[1]) == "--check"

local function readFile(path)
    local f = io.open(path, "r")
    if not f then return nil end
    local text = f:read("*a")
    f:close()
    return text
end

local function files()
    local out = {}
    local pipe = io.popen("ls " .. SOURCE .. "/*.lua")
    for path in pipe:lines() do
        if not path:find("/Libs/") then out[#out + 1] = path end
    end
    pipe:close()
    return out
end

local manifest = {
    functions = {},   -- IMI.Module.Name that the addon defines
    frames    = {},   -- globally named frames it creates
    slash     = {},   -- slash commands it claims
    snippets  = {},   -- secure attributes it sets
    settings  = {},   -- keys it stores
}

local seen = {}
local function add(list, value)
    if value == nil or seen[list] then end
    for _, existing in ipairs(list) do
        if existing == value then return end
    end
    list[#list + 1] = value
end

for _, path in ipairs(files()) do
    local text = readFile(path) or ""

    -- Public functions: "function Edit.RefreshEnemies(" and the like. The
    -- module name comes from the file's own local alias, which every file in
    -- this addon writes the same way.
    local moduleName = text:match("IMI%.(%w+)%s*=%s*{}")
    if moduleName then
        for name in text:gmatch("function%s+" .. moduleName .. "%.(%w+)%s*%(") do
            add(manifest.functions, moduleName .. "." .. name)
        end
    end

    for name in text:gmatch('CreateFrame%(%s*"[%w]+"%s*,%s*"([%w_]+)"') do
        add(manifest.frames, name)
    end

    for command in text:gmatch('SLASH_[%w_]+%d+%s*=%s*"([^"]+)"') do
        add(manifest.slash, command)
    end

    -- Any string literal that names a secure attribute, not only the ones
    -- written straight into a SetAttribute call: four of them are passed as an
    -- argument to a helper, and matching only the direct calls found two of six.
    for attribute in text:gmatch('"(_[%w]+)"') do
        add(manifest.snippets, attribute)
    end
end

-- Settings keys come from one function, and reading them from there rather than
-- from every use site means a key that is written but never defaulted shows up
-- as missing rather than as a key nobody knew about.
local core = readFile(SOURCE .. "/Core.lua") or ""
local block = core:match("local function defaultSettings%(%)%s*return%s*{(.-)\n%s*}")
for key in (block or ""):gmatch("(%w+)%s*=") do
    add(manifest.settings, key)
end

local function sorted(list)
    table.sort(list)
    return list
end

-- Stamped with the version it was built from, so a manifest left behind by an
-- older install is visible in the report rather than silently checked against a
-- different addon.
local version = (readFile(SOURCE .. "/" .. SOURCE .. ".toc") or "")
    :match("## Version:%s*([%d%.]+)") or "unknown"

local out = {
    "--------------------------------------------------------------------------------",
    "-- What this version of the addon contains. Generated by tools/manifest.lua;",
    "-- do not edit by hand, and regenerate when the addon changes:",
    "--",
    "--   lua5.1 tools/manifest.lua",
    "--",
    "-- The self-test compares the running addon against this. Anything here that",
    "-- is missing at run time means the addon and this self-test have come apart,",
    "-- which is worth saying out loud: a check that quietly stopped running looks",
    "-- exactly like a check that passed.",
    "--------------------------------------------------------------------------------",
    "",
    "local ADDON = ...",
    "",
    "InomrahsMISelfTestManifest = {",
}

local function emit(name, list)
    out[#out + 1] = ("    %s = {"):format(name)
    for _, value in ipairs(sorted(list)) do
        out[#out + 1] = ("        %q,"):format(value)
    end
    out[#out + 1] = "    },"
end

emit("functions", manifest.functions)
emit("frames", manifest.frames)
emit("slash", manifest.slash)
emit("snippets", manifest.snippets)
emit("settings", manifest.settings)

out[#out + 1] = ("    builtFor = %q,"):format(version)
out[#out + 1] = "}"
out[#out + 1] = ""

local text = table.concat(out, "\n")

if CHECK_ONLY then
    local existing = readFile(OUTPUT)
    if existing == text then
        print("manifest up to date")
        os.exit(0)
    end
    print("  FAIL: " .. OUTPUT .. " no longer describes the addon.")
    print("        Run: lua5.1 tools/manifest.lua")
    os.exit(1)
end

local file = assert(io.open(OUTPUT, "w"))
file:write(text)
file:close()

print(("Wrote %s"):format(OUTPUT))
print(("  %d functions, %d named frames, %d slash commands, %d snippets, %d settings")
    :format(#manifest.functions, #manifest.frames, #manifest.slash,
            #manifest.snippets, #manifest.settings))
